### ISSUE TITLE
Code for attributes

### ISSUE THREAD

**Issue by jacobtnyoung** [mattduran12/SAND#1]
Hi @mattduran12!

Here is some code to assign an attribute. You can then generalize it to work in the other attributes and years. Let me know if you have questions:

```r

rm( list = ls() )

library( sna )
library( network )
library( dplyr )   # for working with the data


data.2017 <-"https://raw.githubusercontent.com/mattduran12/SAND/main/analytic%20sample-2017.csv"

data.raw.2017 <- read.csv( data.2017, header = TRUE, row.names = NULL )

# take a subset of the first 25 cases so that it is easier to corral and work with 
sub.dat <- data.raw.2017[1:25,]

edgelist <- cbind( 
  sub.dat[,2], # officer as the head node
  sub.dat[,1]  # incident as the tail node
  )


net <- as.network( 
  edgelist, 
  bipartite = length(      # the bipartite count is equal to the length of 
    unique( edgelist[,1] ) # the number of unique ids for officers
  ) 
)


# check vertices were read correctly
length( unique( edgelist[,1] ) )  # number of officers
length( unique( edgelist[,2] ) )  # number of incidents
dim( as.matrix( net ) )           # these should match


# ----
# get the attributes to be the correct length of the nodes

# create an object that is the attribute aggregated to the officer level
attrs <- sub.dat %>% 
  select( off_id, off_gender ) %>% 
  group_by( off_id ) %>% 
  arrange( off_id )

net %v% "gender" <- c( 
  attrs$off_gender, # officer gender 
  rep( NA, dim( as.matrix( net ) )[2] ) # repeat NA to assign to the events
  )

# check a plot to make sure these assignments are correct

cols <- ifelse( net %v% "gender" == "Male", "lightblue", "orange"  )

gplot( net,
       gmode = "twomode",
       usearrows = FALSE,
       label = net %v% "vertex.names" ,
       vertex.col = cols,
       label.cex = 1.5,
       label.pos = 5
       )

# now compare the labels to make sure they match
as.data.frame( attrs )


# So, these match.
# For the event incidents, you would just rework the attrs object
# and the assignment of the attributes

```

**Comment by jacobtnyoung** [comment]
@mattduran12 Did you update the code for this? I was going to check it out

**Comment by mattduran12** [comment]
@jacobtnyoung I did and incorporated some of your code. This is what I came up with:


rm( list = ls() )

library( sna )
library( network )
library( dplyr ) 


data.2021 <-"https://raw.githubusercontent.com/mattduran12/SAND/main/analytic%20sample-2021.csv"
data.raw.2021 <- read.csv(data.2021, header = TRUE, row.names = NULL)
edgelist <- cbind( data.raw.2021[,2], data.raw.2021[,1] )
uof.2021.net <- as.network( 
  edgelist, 
  bipartite = length(      # the bipartite count is equal to the length of 
    unique( edgelist[,1] ) # the number of unique ids for officers
  ) 
)

# Quality assurance; everything matches!
length( unique( edgelist[,1] ) )  # number of officers
length( unique( edgelist[,2] ) )  # number of incidents
dim( as.matrix( uof.2021.net ) )  # these should match

mat.2021 <- as.matrix(uof.2021.net) # coerce network into a matrix

actor_ids <- rownames(mat.2021)
event_ids <- colnames(mat.2021)



officer_genders <- data.raw.2021$off_gender[match(actor_ids, data.raw.2021$off_id)]

# Define colors for males and females
officer_colors <- ifelse(officer_genders == "Male", "orange", "green")

# Define a color for events
event_color <- "blue"

# Combine colors for officers and events
vertex_colors <- c(officer_colors, rep(event_color, length(event_ids)))

gplot(
  uof.2021.net,
  gmode = "twomode",
  usearrows = FALSE,
  vertex.col = vertex_colors,
  edge.col="grey60",
  label.cex = 1.2,
  main = "2021 - UoF Count"
)
