### ISSUE TITLE
Code for ERGM

### ISSUE THREAD

**Issue by mattduran12** [mattduran12/SAND#2]
@jacobtnyoung Hi Dr. Young,

1. I incorporated the code you wrote and now have a script that transforms a year of UOF data into a bipartite network with officer and incident attributes.
2. I have successfully been able to generate cool looking plots.
3. I have not been able to figure out how to run an ERGM with a bipartite network object.
4. Because of this, I have not started messing with the b1nodematch function to figure that out.

Would you mind helping me out with 3 and 4? I created a script for you to work off of. It's called "ergm-Duran-code.R" in my repository.

Thanks for your help.

**Comment by jacobtnyoung** [comment]
Hi @mattduran12. Will do. I updated the code. A few things:

  * There was an error in the assignment for the gender variable. 
  * Check to make sure that for an attribute for a first node has values of NA for the second node set.
  * I added code for the ergm to get started.

**Comment by jacobtnyoung** [comment]
Hi @mattduran12, let me know if you have questions about how to merge the commits I pushed to the repo.
