### ISSUE TITLE
ERGM

### ISSUE THREAD

**Issue by mattduran12** [mattduran12/SAND#4]
@jacobtnyoung

Is it possible to test an edge attribute? I have assigned an edge attribute ("Ties")  to my network object "net". The attribute is a continuous variable. I'm attempting to figure it out but running into trouble. Thank you.

library(ergm)
ergm.net <- ergm( 
  net ~ edges 
  + edgecov("Ties")
) 

summary( ergm.net )

**Comment by jacobtnyoung** [comment]
Hi @mattduran12   It is. And you have the correct term. If you create a script in your repo with the code for reproducing the error I can check it out 🤙🏼

**Comment by mattduran12** [comment]
@jacobtnyoung 

I uploaded my script. The file is called, "2021-partners-code.R" - **The bottom of my script is where I am running ERGMs**

Here's a quick rundown of what's going in there, and my thoughts to help me think through what's going on.

1. I took the officer/incident network and projected a one-mode officer matrix.
2. I then take this one-mode officer matrix and transform it into a network that captures the frequency of unique officer combinations (i.e., officers that share more than one incident together), what I call a "partners" network.
3. The edge attribute assigned is the frequency of shared incidents.


After doing some more thinking, I messed up. My one-mode officer matrix is being reduced into "partners" (i.e., nodes are now unique two-officer combinations) with a number of shared use of force incidents (referred to as "Ties" in the actor_pairs2 dataframe). Where I messed up is that I assigned a single attribute to these nodes, when they are in fact pairs of officers. I'm going to hold off on the code ofthe "partners" network and instead focus on the one-mode projection that I initially ran.

Example of partners network:
Officers (3488 / 3484) had 3 shared incidents.

**Comment by jacobtnyoung** [comment]
Hi @mattduran12, I am confused by #2 and #3. The frequency of shared incidents is just the projection; the weighted matrix.

You can incorporate that information into the network object using the `ignore.eval=` and `names.eval=` arguments in the `as.matrix` function. For example:

```r

rm( list = ls() )
library( sna )
library( network )
library( dplyr ) 
data.2021 <-"https://raw.githubusercontent.com/mattduran12/SAND/main/final%20data%20(2017-2022).csv"
data.raw.2021 <- read.csv(data.2021, header = TRUE, row.names = NULL)
data.raw.2021 <- data.raw.2021 %>% filter(year == 2021)
edgelist <- cbind( data.raw.2021[,2], data.raw.2021[,1] )
uof.2021.net <- as.network( edgelist, bipartite = length(unique( edgelist[,1] ) ) )
mat.2021 <- as.matrix(uof.2021.net)
mat.2021.P <- mat.2021 %*% t( mat.2021 )


###HERE!!!

# create the network object and assign the weights as an attribute

net.2021.P <- as.network( mat.2021.P,
                          ignore.eval = FALSE,     # tells function to not ignore the values of the input matrix
                          names.eval = "incidents" # sets the name for the edge weights
                          )

# return the edge weights using the get.edge.attribute operator
net.2021.P %e% "incidents"

# plot it
gplot( net.2021.P,
       gmode = "graph",
       vertex.col = "grey60",
       edge.col = net.2021.P %e% "incidents", # this will take some playing with to get it to work
       edge.lwd = net.2021.P %e% "incidents"*0.5 #this will take some playing with also
       )

``` 

Is that what you are trying to do?

**Comment by jacobtnyoung** [comment]
Then @mattduran12 , you can use the `ergm.count` model that is for count data. Like this:

```r

# after running the code above

library( ergm.count )

exampleMod <- ergm( net.2021.P 
                    ~ sum ,                 
                    response = "incidents", 
                    reference = ~ Poisson 
                    )

```

Here is a good tutorial: https://statnet.org/workshop-valued/valued.html.

**Comment by mattduran12** [comment]
Thank you!
