### ISSUE TITLE
Did I project the network properly?

### ISSUE THREAD

**Issue by mattduran12** [mattduran12/SAND#5]
Hi @jacobtnyoung ,

I am reporting the raw degree centrality scores for my projected officer-officer network, and I am surprised to see that the minimum degree score is 0. I was expecting to see 1 as the minimum value because the bipartite network contains incidents that involved two or more officers; single-officer use of force incidents were removed from the csv file .

Would you mind double-checking this in case I am missing something? Lines 1 to 179 contain all the relevant code. Lines 176-179 is where I am calculating the degree centrality scores.

Thanks for your help!

-Matthew

**Comment by jacobtnyoung** [comment]
Hi @mattduran12 . I will check it out tomorrow.  🤙🏼

**Comment by jacobtnyoung** [comment]
Hi @mattduran12 . This is weird. The problem is when it is converted to a network object. See the script below:

```r

rm( list = ls() )

library( sna )
library( network )
library( dplyr ) 

data.2021 <-"https://raw.githubusercontent.com/mattduran12/SAND/main/final%20data%20(2017-2022).csv"
data.raw.2021 <- read.csv(data.2021, header = TRUE, row.names = NULL)

data.raw.2021 <- data.raw.2021 %>%
  filter(year == 2022)
data.raw.2021 <- data.raw.2021 # %>%
#filter(off_race >2) # excludes Alaskan Native/ and Asian pacificlander for ERGM


edgelist <- cbind( data.raw.2021[,2], data.raw.2021[,1] )
uof.2021.net <- as.network( 
  edgelist, 
  bipartite = length(      # the bipartite count is equal to the length of 
    unique( edgelist[,1] ) # the number of unique ids for officers
  ) 
)

mat.2021 <- as.matrix( uof.2021.net ) # coerce network into a matrix

mat.2021.P <- mat.2021 %*% t( mat.2021 )


sort( rowSums( mat.2021.P ) ) # nobody at degree zero

which( rowSums( mat.2021.P ) == 0 )  # nobody at degree zero


mat.2021.P.net <-as.network(
  mat.2021.P,
  directed = FALSE )


deg <- degree(mat.2021.P.net, gmode = "graph", cmode = "degree")

min( deg )

sort( rowSums( as.matrix( mat.2021.P.net ) ) )
which( sort( rowSums( as.matrix( mat.2021.P.net ) ) ) == 0 ) # 2839 is 0

table( network.vertex.names( mat.2021.P.net ) == 2839 )

# 2839 has 2 ties in the adjacency matrix
table( mat.2021.P["2839",] )
sort( mat.2021.P["2839",] )

```

2839 has degree 2 in the projection, but is not connected to anyone else. Make sense?

**Comment by mattduran12** [comment]
I found the issue, error on my end with the data management. That officer was involved in a use of force incident with an officer from a lateral transfer cohort, which was overall small and dropped.

Thanks for helping me figure this out!

**Comment by jacobtnyoung** [comment]
Hi @mattduran12 , that makes sense. Glad you figured it out and happy to help!
